[project]
name = "rest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.8.1",
    "huggingface-hub[cli]>=0.33.4",
    "torch>=2.7.1",
]
